
image: gitpod/workspace-postgres

tasks:
  - init: npm install
    env:
      DATABASE_URL: postgres://gitpod@localhost/ideas

ports:
  - port: 5173
    onOpen: open-browser
  - port: 5432

vscode:
  extensions:
    - Prisma.prisma
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss
